# Generated by Django 4.0.6 on 2022-08-24 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('duration', models.TimeField()),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=400)),
                ('language', models.CharField(choices=[('PE', 'Persian'), ('EN', 'English')], default='EN', max_length=2)),
                ('message', models.CharField(max_length=400)),
                ('url', models.CharField(max_length=128, unique=True)),
                ('color', models.CharField(max_length=100)),
                ('finaltime', models.DateTimeField(null=True)),
                ('timestatus', models.CharField(choices=[('Ch', 'Choosing'), ('Fn', 'Finalized')], default='Ch', max_length=2)),
                ('ownerID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ownermeet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserMeet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meetID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Meeting.meeting')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OwnerAvailableTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Sat', 'Saturday'), ('Sun', 'Sunday'), ('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wen', 'Wendsday'), ('Thu', 'Thursday'), ('Fri', 'Friday')], default='Sat', max_length=3)),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('meetID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Meeting.meeting')),
            ],
        ),
        migrations.AddField(
            model_name='meeting',
            name='users',
            field=models.ManyToManyField(related_name='meetusers', through='Meeting.UserMeet', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AvailableTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Meeting.usermeet')),
            ],
        ),
    ]
