# Generated by Django 4.0.6 on 2022-08-24 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Meeting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerAvailableTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Sat', 'Saturday'), ('Sun', 'Sunday'), ('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wen', 'Wendsday'), ('Thu', 'Thursday'), ('Fri', 'Friday')], default='Sat', max_length=3)),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('meetID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Meeting.meeting')),
            ],
        ),
        migrations.CreateModel(
            name='AvailableTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtime', models.DateTimeField()),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Meeting.usermeet')),
            ],
        ),
    ]
